.PHONY: lint
lint:
	@golangci-lint run ./...
	@go-consistent ./...

.PHONY: lint-fix
lint-fix:
	@golangci-lint run --fix ./...
	@go-consistent ./...

.PHONY: test
test:
	@go test -race -cover -count 1 ./...

.PHONY: coverage
coverage:
	@go test -race -count -coverpkg=./... -coverprofile=coverage.txt ./...